### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [Toblerity/Shapely#1015]
**Summary**
Installing shapely on aarch64 via pip using command "pip3 install shapely" tries to build wheel from source code.

**Problem description**
shapely doesn't have wheel for aarch64 on PyPI repository. So, while installing shapely via pip on aarch64, pip builds wheel for same resulting in it takes more time to install shapely. Making wheel available for aarch64 will benefit aarch64 users by minimizing shapely installation time.

**Expected Output**
Pip should be able to download shapely wheel from PyPI repository rather than building it from source code.

@shapely-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make shapely wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by sgillies** [comment]
@odidev the infrastructure for building shapely's wheels is in https://github.com/shapely/shapely-wheels. That project uses multibuild to make the wheels. I think code from https://github.com/python-pillow/pillow-wheels/blob/55e6fe4b6bdb852c6b10aaff96f29aa66154a74e/.travis.yml#L97-L103 could be adapted to work for Shapely. I'm going to close this issue, since it's something that has to be fixed downstream in https://github.com/shapely/shapely-wheels. Can you open a new issue there?
