### ISSUE TITLE
Error with fonctions within and contains 

### ISSUE THREAD

**Issue by straleuse** [Toblerity/Shapely#1189]
Working on Jupyther Notebook v2.3.2
Working with lastest GeoPandas and Shapely librairies
 
I am currently trying to check if a point existing in a polygon with shapely but unfortunately it doesn't seem to work. 
My little script to test it is the following : 

p1 = Polygon([(1.0, 1.0), (1.0, -1.0), (-1.0, -1.0), (-1.0, 1.0), (0.0, 0.0)])
c = [-0.1,0.1]
pc = Point(c)
print(pc.within(p1))

In this case the result giving False but it should be True. If you have an idea of the problem I have, I would enjoy speaking with you.
Best regards and thank you for all the work you do on this librairy.

**Comment by mwtoews** [comment]
Here is an image of the overlay:
![image](https://user-images.githubusercontent.com/895458/131668609-708e055c-b516-43de-838e-4744769cd655.png)

This is the expected result, because the point is on the exterior of the polygon, and is not contained by the interior. (`p1.relate(pc)` returns `FF20F1FF2`; see [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM) to unravel what this means)

Perhaps you want `pc.intersects(p1)`?

**Comment by straleuse** [comment]
I am sorry I am using folium to check on map, but unfortunately I missed the fact that folium takes latitude then longitude, which is not the case of shapely :(  
Thank you for the answer
