### ISSUE TITLE
Feature request: Return index of line where intersection occurs.

### ISSUE THREAD

**Issue by tim-blackmore** [Toblerity/Shapely#1247]
I have ported a project from Matlab to Python, and my biggest disappointment is the time it is taking me to identify the index at which an intersection occurs. In Matlab I used a function called [polyxpoly ](https://uk.mathworks.com/help/map/ref/polyxpoly.html)from the Mapping toolbox where returning the index is provided as an option. Right now I am having to [loop through](https://stackoverflow.com/questions/69996695/find-indices-of-line-intersection-in-shapely) the location coordinates another time (much less efficiently than Shapely) and locate it myself.

Therefore, would it be possible to consider outputting the index of the line where the intersection occurs. This has also been raised [elsewhere](https://gis.stackexchange.com/questions/339409/find-the-vertices-of-the-edge-of-the-polygon-where-line-intersects-using-shapely/339454#339454?newreg=9aa692cca263442099986a078de51ce4).

**Comment by sgillies** [comment]
@tim-blackmore are you saying that, given a pair of poly-lines, you'd like to quickly know not only their point of intersection but the identities of the intersecting segments in each input? 

I suspect that this kind of information is used in the GEOS intersection algorithm (see https://github.com/libgeos/geos/tree/main/src) but it is not surfaced in the library's API. So, the shapely project would have to use brute force as well. I don't think we will develop this feature unless someone comes up with an algorithm better than looping through all vertices.

**Comment by tim-blackmore** [comment]
@sgillies I can confirm this is what I am asking. Thanks for considering it, I am using a loop myself at the moment so I will stick with that. 

For anyone reading this, I did find a moderate speed up by using intersects rather than intersection as I don't need the coordinates.

**Comment by sgillies** [comment]
Thanks for the response @tim-blackmore. I'm sorry that shapely doesn't have quite what you need. At least the low-level pieces are there: you can explode the polylines into parts, organize them in an R-tree, and make a matrix of parts that intersect.

Someday I hope to find the time to write more about shapely's level(s) of abstraction and what and isn't important to them. Often, the coordinate values we pass to shapely geometry constructors; or their indices, order, or identity, are important to the applications we build. They are not, however, important to shapely except as parameterizations of sets of points. `LineString([(0, 0), (2, 2)])` and `LineString([(0, 0), (1, 1), (2, 2)])`, for example, are basically the same thing because they describe the same mathematical sets of points.
