### ISSUE TITLE
Batteries included binary wheels for OS X

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Shapely#224]
I uploaded a Shapely 1.5.2 binary wheel for OS X to https://pypi.python.org/pypi/Shapely#downloads. As explained in #221 this wheel contains the GEOS shared library and gives us a self-contained Shapely binary much like the Windows installer.

On OS X with pip version >=6.0 you'll get this wheel when you `pip install shapely`. It's compatible with pythons from the OS X system, python.org, Homebrew, probably any python built with OS X >=10.6. If you don't want to use the wheel, preferring to use your system's shared GEOS lib, do `pip install shapely --no-use-wheel`. Documentation of this is coming up.

If your pip version is <6, you won't get this wheel unless you're using a Python from python.org.

Lemme know how it goes and help spread the word that Shapely is easier to install and use on OS X than ever.

**Comment by jwass** [comment]
Awesome!

**Comment by olt** [comment]
A user of Imposm reported some issues with 1.5.3 on Mac OS X. I didn't followed the development of the wheel packages until now. Here are my observations:

Shapely tries to load `GEOS` from the `.dylibs` dir but my installation only contains a `libgeos_c.1.dylib` and `libgeos-3.4.2.dylib`. See: https://github.com/Toblerity/Shapely/blob/master/shapely/geos.py#L65
Shapely still works because it finds a `libgeos_c` in my `/usr/local/lib` but it crashes when I enable the speedups.

Here is a one-liner that crashes on my system (10.10 with homebrew geos):

    % python -c 'from shapely import speedups; assert speedups.available; speedups.enable(); from shapely.geometry import LineString; LineString([(0, 0), (10, 0)]).wkt'
    Assertion failed: (0), function appendGeometryTaggedText, file WKTWriter.cpp, line 227.
    Abort trap: 6

**Comment by sgillies** [comment]
@olt confirmed... "GEOS" was left over from trying to do this with a GEOS framework. 1.5.4 coming right up...
