### ISSUE TITLE
shapely.geometry.mapping() returns values that don't strictly follow the GeoJSON spec

### ISSUE THREAD

**Issue by aronbierbaum** [Toblerity/Shapely#245]
Calling the following returns a Python dictionary that doesn't completely follow the GeoJSON specification [1] because it returns the coordinates as a `tuple` instead of a `list`. This may not be an issue because when we encode the dictionary it converts the tuple to a list. It can make testing the value challenging though. For example if we create the GeoJSON, save it to a database and read it again the dictionary will be different.

```
>>> import shapely.geometry
>>> shapely.geometry.mapping(shapely.geometry.Point(0.0, 1.0))
{'type': 'Point', 'coordinates': (0.0, 1.0)}
>>> json.loads(json.dumps(shapely.geometry.mapping(shapely.geometry.Point(0.0, 1.0))))
{u'type': u'Point', u'coordinates': [0.0, 1.0]}
```

[1] http://geojson.org/geojson-spec.html

**Comment by snorfalorpagus** [comment]
Is the issue here that JSON doesn't make a distinction between `tuples` and `lists`, as it only has a single `array` object? The [`__geo_interface__` protocol](https://gist.github.com/sgillies/2217756) is described as "GeoJSON-like", rather than strict GeoJSON. I believe that the reason shapely returns tuples for the coordinate sequences is that shapely geometries are supposed to be immutable (i.e. they shouldn't be changed once they are created).

For interest, the implementation of `__geo_interface__` in QGIS returns a list of coordinates:
```
g = QgsGeometry.fromPoint(QgsPoint(0,0))
g.__geo_interface__
{'type': 'Point', 'coordinates': [0, 0]}
```
I'm sure @sgillies can provide a more authoritative answer...

**Comment by sgillies** [comment]
@aronbierbaum @snorfalorpagus another thing that makes me want to keep tuples is that I keep asking myself "why shouldn't these be *namedtuples* instead of ordinary tuples?"

**Comment by snorfalorpagus** [comment]
@sgillies Looking at the documentation for this I can't see a reason why not either. In fact, the example given is a Point class that exposes .x and .y names!

"Named tuple instances do not have per-instance dictionaries, so they are lightweight and require no more memory than regular tuples."

https://docs.python.org/2/library/collections.html#collections.namedtuple

And they are still iterable, so promote to `Point` (or more complex geometries) nicely.

```
>>> from shapely.geometry import Point
>>> from shapely.geometry import LineString
>>> from collections import namedtuple
>>> P = namedtuple('P', ['x','y'])
>>> p1 = P(0,0)
>>> p2 = P(1,2)
>>> p1.x, p1.y
(0, 0)
>>> Point(p1)
<shapely.geometry.point.Point object at 0x03789390>
>>> Point(p1).wkt
'POINT (0 0)'
>>> Point(p2).wkt
'POINT (1 2)'
>>> LineString([p1, p2]).wkt
'LINESTRING (0 0, 1 2)'
```

**Comment by snorfalorpagus** [comment]
Some quick testing indicates that using `namedtuple`s instead of `tuple`s incurs a significant performance hit when iterating over large numbers of coordinates in Fiona, e.g. looping through all the coordinates in a collection. Something in the order of 50% slower. We could probably achive something faster by writing dedicated Coord2D and Coord3D classes in Cython.

**Comment by sgillies** [comment]
Closing.
