### ISSUE TITLE
unary_union and cascaded_union error when using more than 4 polygons

### ISSUE THREAD

**Issue by nathancahill** [Toblerity/Shapely#288]
I have a list of 80 polygons that I'm trying to merge. If I pick any 5 of the 80, I get an error. Less than 5 works fine. The error happens with both `unary_union` and `cascaded_union`

Here are 5 random polygons from the list:

```
POLYGON ((-13227886.36691946 3952711.606683034, -13208318.48767846 3952711.606683034, -13208318.48767846 3933143.727442028, -13227886.36691946 3933143.727442028, -13227886.36691946 3952711.606683034))
POLYGON ((-13169182.72919645 4050551.002888059, -13149614.84995544 4050551.002888059, -13149614.84995544 4030983.123647054, -13169182.72919645 4030983.123647054, -13169182.72919645 4050551.002888059))
POLYGON ((-13130046.97071444 4050551.002888059, -13110479.09147343 4050551.002888059, -13110479.09147343 4030983.123647054, -13130046.97071444 4030983.123647054, -13130046.97071444 4050551.002888059))
POLYGON ((-13090911.21223243 4030983.123647054, -13071343.33299142 4030983.123647054, -13071343.33299142 4011415.244406049, -13090911.21223243 4011415.244406049, -13090911.21223243 4030983.123647054))
POLYGON ((-13306157.88388348 4226661.916057106, -13149614.84995544 4226661.916057106, -13149614.84995544 4070118.882129065, -13306157.88388348 4070118.882129065, -13306157.88388348 4226661.916057106))
```
Here's the full list: https://gist.github.com/nathancahill/2c24c70f8b074859442f

Error:

> Assertion failed: (!"should never be reached"), function itemsTree, file AbstractSTRtree.cpp, line 371.
> Abort trap: 6

Digging into this a bit more when I tried to `.union()` the polygons one by one. It raises this error:

> Assertion failed: (0), function query, file AbstractSTRtree.cpp, line 285.
> Abort trap: 6

The comment on that line says: `assert(0); // unsupported childBoundable type`

**Comment by snorfalorpagus** [comment]
Possibly related to #259?

I can't reproduce this error.

**Comment by nathancahill** [comment]
Hmm, looks like the same error, but installing with `--no-install-wheel` did not fix the issue. I have GEOS 3.4.2 installed via Homebrew.

**Comment by sgillies** [comment]
@nathancahill this issue is resolved at https://github.com/Toblerity/Shapely/issues/262#issuecomment-97555385. Looking in the [GEOS Homebrew formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/geos.rb) I see that C asserts aren't disabled like they should be; Homebrew's GEOS is unfortunately built in debug mode. The solution is to add `--disable-cassert` after https://github.com/Homebrew/homebrew/blob/master/Library/Formula/geos.rb#L30.

**Comment by nathancahill** [comment]
Thanks @sgillies! Works perfectly now.

**Comment by sgillies** [comment]
:relieved:

**Comment by youngpm** [comment]
@sgillies I just encountered this.  Installing fiona and shapely via the osx wheels and then unary unioning a multipolygon (with 100 guys in it) results in (python 3.5 on OSX):
```
In [1]: import fiona
In [2]: import json
In [3]: from shapely import geometry, ops
In [4]: with open('../flamedra/testdata/cloud/10300100106D9000.geojson') as src:
   ...:     d = json.load(src)
In [5]: mp = geometry.shape(d['geometry'])
In [6]: ops.unary_union(mp)
Out[6]: <shapely.geometry.collection.GeometryCollection at 0x106349fd0>

In [7]: len(_)
Out[7]: 0
```
Dropping the `fiona` import (or putting shapely's imports first), I get the expected behavior,
```
In [1]: import json
In [2]: from shapely import geometry, ops
In [3]: with open('../flamedra/testdata/cloud/10300100106D9000.geojson') as src:
   ...:     d = json.load(src)
In [4]: mp = geometry.shape(d['geometry'])
In [5]: ops.unary_union(mp)
Out[5]: <shapely.geometry.multipolygon.MultiPolygon at 0x1103f4d30>
In [6]: len(_)
Out[6]: 100
```
My wild guess is that the vendorized gdal that is coming with fiona has a geos with the asserts enabled and that's conflicting.  The same thing happens if I import `rasterio==1.0a2`.  

Also, it looks like the change to brew seems to have been reverted?  Maybe a red herring.  

https://github.com/Homebrew/homebrew-core/blob/master/Formula/geos.rb#L36-L39

**Comment by sgillies** [comment]
@youngpm I have a hunch that you're right about the GEOS asserts. I've uploaded new wheels that are consistent with each other (Shapely, Fiona, and Rasterio) and am doing a better job tracking which version of https://github.com/sgillies/frs-wheel-builds is used to generate wheels.

**Comment by gerardsimons** [comment]
I am still getting this issue as well on Mac OS. The original link for editing the rb file is rotten, can anybody assist? Where should I add `--disable-cassert`?
