### ISSUE TITLE
Polygon contains() documentation bug

### ISSUE THREAD

**Issue by tinloaf** [Toblerity/Shapely#290]
Hi,

the documentation for contains() states: "Returns True if the object’s interior contains the boundary and interior of the other object and their boundaries do not touch at all."

Consider this:
```
>>> from shapely.geometry import Polygon
>>> outer = Polygon(((0,0), (0, 10), (10, 10), (10, 0), (0,0)))
>>> inner = Polygon(((0,0), (0,5), (5, 5), (5,0), (0,0)))
>>> outer.contains(inner)
True
```

Obviously, the boundaries in this case *do* touch. It looks more like contains() checking just whether the interior of inner is completely contained in the interior of outer, without considering the boundaries.

**Comment by bixb0012** [comment]
I agree the Shapely wording for `object.contains()` is not correct.  That said, `object.contains()` isn't quite as simple as the interior of an object being completely contained by the interior of another object without considering the boundaries.

Since Shapely geospatial operators are mostly or wholly [GEOS](http://trac.osgeo.org/geos/) spatial operators, and GEOS `objects.contains()` implements the Dimensionally Extended 9 Intersection Model (DE-9IM), looking at the DE-9IM contains mask is helpful:  `T*****FF*`.  The interiors must intersect, to some extent, but that doesn't disallow the interior of an object from also intersecting the boundary of the outer object.

```python
>>> from shapely.geometry import Polygon, LineString
>>> outer = Polygon(((0,0), (0, 10), (10, 10), (10, 0), (0,0)))
>>> inner = LineString(((0, 0), (5, 0), (5, 5)))
>>> boundary = LineString(((0, 0), (5, 0)))
>>> outer.contains(inner)
True
>>> outer.contains(boundary)
False
>>> 
```

**Comment by sgillies** [comment]
@bixb0012 Do you want to suggest a concrete improvement to the documentation's text or perhaps submit a PR?
