### ISSUE TITLE
np.array(geom) returning array with all values = 0.0 when used with MacPorts geos 3.5.0

### ISSUE THREAD

**Issue by shongololo** [Toblerity/Shapely#335]
I have been using the np.array(geom) functionality for some time, but have suddenly been finding that it returns numpy arrays (of the correct shape) with 0.0 for all values.

When experimenting from the console with basic geometries, I am unable to reproduce the issue.

Any ideas for how to tackle this?

UPDATE: When trying to create test geometry in the same environment it fails and gives me this error:
<code>Assertion failed: (0 != cs), function GEOSCoordSeq_setOrdinate_r, file geos_ts_c.cpp, line 3408.</code>

FURTHER UPDATE: The problem occurs when using the MacPorts installed version of geos:
<code>DEBUG:shapely.libgeos:geos-config --clibs: '-L/opt/local/lib -lgeos_c' 
DEBUG:shapely.libgeos:found GEOS C library using geas-config</code>

When force uninstalling that version, it finds the version installed with anaconda's installer, which seems to work fine:
<code>DEBUG:shapely.libgeos:geos-config --clibs: '-L/Users/shongololo/anaconda/lib -lgeos_c'
DEBUG:shapely.libgeos:found GEOS C library using geas-config</code>

QUESTION: Is there a way to set the preferred geos library from the script?

Thanks.

**Comment by shongololo** [comment]
UPDATE: I checked my .bash_profile and it turns out that MacPorts had placed its path in front of the anaconda path, so when loading the Shapely package it was finding the macports installed version of geos instead of the anaconda version of geos.

Per above, it doesn't seem to work with the MacPorts version of geos (3.5.0) but does work with the Anaconda version of geos (3.3.3)

**Comment by sgillies** [comment]
@shongololo if you have multiple installations of GEOS on your computer and aren't certain about the order in your PATH, I recommend `GEOS_CONFIG=path/to/geos-config python setup.py ...`.

I see from your examples above that you have either an out of date Shapely 1.5.x or an unreleased version of Shapely from its repo. There's no `shapely.libgeos` module in Shapely 1.5.13. It was removed to simplify discovery of GEOS at run time.

By "suddenly" do you mean since a Numpy upgrade? I've been noticing a bunch of problems in Rasterio with 1.10, I haven't tested Shapely with 1.10 yet.

**Comment by shongololo** [comment]
@sgillies I am using the Anaconda version of shapely, which is probably a little outdated. (Anaconda sometimes forces old versions for the sake of compatibility with other packages). It was working fine until I installed geos via MacPorts, which is what the 'suddenly' referred to.

I've edited the PATH to place the Anaconda version of geos ahead of that from MacPorts, and since then it is working nicely again. Thanks.
