### ISSUE TITLE
Shapely intersections vs shapely relationships - inexact?

### ISSUE THREAD

**Issue by vectorien** [Toblerity/Shapely#346]
Hi I wonder if I am thinking the wrong way or if this is a bug:

I have a linestring and a polygon,
I create the intersection points of the line and the polygon's boundary

[![enter image description here][1]][1]

These intersection points should intersect (at least touch) the polygon's boundary, right?

    from shapely import geometry,wkt
    line = geometry.LineString([(13.51039642756912, 52.598912814414675), (13.525173800277184, 52.60620240344557)])
    poly = geometry.Polygon ([(13.52072838433517, 52.61735554606274), (13.52233276805985, 52.59511541819082), (13.51312087418833, 52.59394589806786),( 13.51526963068252, 52.60338701649216),( 13.51836560008325 ,52.6009395669487), (13.52072838433517, 52.61735554606274)])
    
    ips = line.intersection(poly.boundary)
    for i in ips:
    	print i.touches(poly.boundary)# should touch but it doesnt!!!!
    	print i.relate(poly.boundary)

  [1]: http://i.stack.imgur.com/NW2ez.png

**Comment by mwtoews** [comment]
It's not a bug, but this is a frequent question.

Without a precision model, all floating point calculations are limited by the [machine epsilon](https://en.wikipedia.org/wiki/Machine_epsilon). The intersected points are interpolated from each geometry, and are seldom exact (unless you have right angles). All of the DE-9IM predicates like 'touches' currently require exact noding (unless we have a precision model, which might happen one day).

A more robust strategy is to test the distance between the two, which should be less than the machine epsilon if they intersect. E.g.:
```python
EPS = 1e-15
for i in ips:
    print i.distance(poly) < EPS
```

**Comment by vectorien** [comment]
Hi , thanks, do you mind if I copy your answer to http://stackoverflow.com/questions/33883690/shapely-intersections-vs-shapely-relationships-inexact

**Comment by bixb0012** [comment]
@mwtoews, I agree this isn't a bug, but I disagree about why.  At least in this case, it is about definition and not precision.

The OP is testing/checking whether 4 points generated from intersecting a line with a polygon 'touch' the boundary of that polygon.  Since Shapely implements [GEOS](http://trac.osgeo.org/geos) and GEOS is Simple Feature compliant, the behavior being seen is expected.

Looking to the [Simple Feature Access](http://www.opengeospatial.org/standards/sfa) standard, and thus the Dimensionally Extended nine-Intersection Model ([DE-9IM](https://en.wikipedia.org/wiki/DE-9IM)), one geometry 'touches' another if the geometries "have at least one boundary point in common, but no interior points."  Since the boundary of a polygon is a line/linestring and the boundary of a linestring is its endpoints (according to DE-9IM), a point cannot 'touch' the boundary of a polygon unless it has the same coordinates as one of the boundary's endpoints.
```Python
>>> from shapely import wkt
>>> 
>>> ln = wkt.loads('LINESTRING(0 0, 2 0)')
>>> pt_a = wkt.loads('POINT(0 0)')
>>> pt_b = wkt.loads('POINT(1 0)')
>>> 
>>> pt_a.touches(ln)
True
>>> pt_b.touches(ln)
False
>>> 
>>> pt_a.intersects(ln)
True
>>> pt_b.intersects(ln)
True
>>> 
```
With the OP's example, none of the 4 points touch the boundary of the polygon in question, by definition.  That said, all 4 points intersect the boundary of the polygon in question.

**Comment by vectorien** [comment]
Well @bixb0012  the 4 points in my example do return false for the intersects tests:

```
from shapely import geometry,wkt
line = geometry.LineString([(13.51039642756912, 52.598912814414675), (13.525173800277184, 52.60620240344557)])
poly = geometry.Polygon ([(13.52072838433517, 52.61735554606274), (13.52233276805985, 52.59511541819082), (13.51312087418833, 52.59394589806786),( 13.51526963068252, 52.60338701649216),( 13.51836560008325 ,52.6009395669487), (13.52072838433517, 52.61735554606274)])

ips = line.intersection(poly.boundary)
for i in ips:
    print i.intersects(poly.boundary)# should intersect but it doesnt!!!!
    print i.relate(poly.boundary)

```

**Comment by mwtoews** [comment]
@bixb0012 Regardless of precision issues, I think the correct spatial predicate for the question should have been 'intersects', because 'touches' may provide unexpected outcomes between lines and points (as demonstrated between `pt_a` and `pt_b`).

But it is a misconception that 'touches' needs to have the same coordinates as one of the boundary's. Continuing from your example, these lines touch, but have no common coordinates:
```python
ln_b = wkt.loads('LINESTRING(1 0, 1 1)')
ln.touches(ln_b)  # True
ln.relate(ln_b)  # F01FF0102
```

The point I was making above is that there are precision errors where interpolations are required. So rotating `ln` and `ln_b` will yield different outcomes depending on the precision of your computer. This example with 'touches' will be a mixed bag of `True` and `False` results for different angles of rotation and the placement of the common pivot point:
```python
>>> from shapely import affinity
>>> p = wkt.loads('POINT(2 2)')  # common pivot point
>>> for a in range(0, 360):
...     print('%d: %s' % (a, affinity.rotate(ln, a, p).touches(affinity.rotate(ln_b, a, p))))
... 	
0: True
1: False
2: False
3: True
4: False
5: True
6: False
7: True
8: True
...
```

**Comment by mwtoews** [comment]
Oh, and unfortunately, it seems that the implemented precision model is not used for spatial predicates. Or at least with JTS this is the situation, therefore I don't expect GEOS to be any different. So using `intersects` without exact noding will continue to be problematic, unless the precision model is extended for DE-9IM.

**Comment by bixb0012** [comment]
@vectorien, interesting, I should have doubled checked using your original data.  That said, there was a definition issue on top of the precision issue.

**Comment by bixb0012** [comment]
@mwtoews, thanks for pointing out the text I quoted was incorrect.  Barring that oversight, the rest of my comment looks all right.  Since a point doesn't have a boundary, it can only 'touch' a line on its end points; otherwise, the point and the line would have some interior points in common.  Since a line has a boundary, it can 'touch' another line on its interior like in the example you provided.

My stab at summarizing the OP's example in the context of DE-9IM:  "The points where the line intersects the polygon boundary touch the polygon on its boundary, but those same points don't touch the boundary itself."
