### ISSUE TITLE
Arm build failures

### ISSUE THREAD

**Issue by stratakis** [Toblerity/Shapely#372]
When building for fedora 24 and rawhide, for the arm v7 architecture, all tests from test_vectorized.py are failing with the message: OverflowError: Python int too large to convert to C long.

Full build log: https://kojipkgs.fedoraproject.org//work/tasks/7357/13207357/build.log

**Comment by snorfalorpagus** [comment]
Looks like `_geos.pxi` is using a `long` to store pointers, instead of `uintptr_t`, which is causing an overflow.

https://github.com/Toblerity/Shapely/blob/master/shapely/_geos.pxi#L4

This should be an easy fix but I don't have a machine running on ARM v7 to test (I'm guessing you have a Raspberry Pi 2?). If I make the change in a branch are you willing to test?

**Comment by stratakis** [comment]
Yep I will test it.

**Comment by snorfalorpagus** [comment]
@stratakis I've made the change here: https://github.com/snorfalorpagus/Shapely/tree/ptr

It's only 3 lines. Depending on how comfortable you are with git, it may be easier to make the changes manually: https://github.com/snorfalorpagus/Shapely/commit/9f123a686dbf50fd07d8a1daa4fcffdf808942ed

If this works I'll create a PR for it to be merged into the maint branch (1.5.x).

**Comment by stratakis** [comment]
Test build completed successfully for ARM.
http://koji.fedoraproject.org/koji/taskinfo?taskID=13447729

Issue is resolved. Thank you very much for looking into it.

**Comment by stratakis** [comment]
Seems that this fix wasn't implemented in the 1.5.14 source code.

**Comment by sgillies** [comment]
@stratakis you're right... I didn't notice that I'd merged to maint and not maint-1.5, the branch from which 1.5.x releases are made. 1.5.15 coming up...
