### ISSUE TITLE
Line contains Point returns False when it shouldn't

### ISSUE THREAD

**Issue by IvKor** [Toblerity/Shapely#423]
Trying to figure whether the point lies on the line and I think I found a bug in the Shapely

```
from shapely.geometry import LineString, Point
coords = [(0, 0), (2.1, 1.2)]
print(LineString(coords).contains(Point(0.7, 0.4)))
print(Point((0.7, 0.4).within(LineString(coords)))
```

Everything works fine when scaled up by 10 but I cannot figure why the initial statements return False in both cases.
```
coords = [(0, 0), (21, 12)]
print(LineString(coords).contains(Point(7, 4)))
print(Point(7, 4).within(LineString(coords)))
```

**Comment by sgillies** [comment]
@IvKor `contains` is unreliable at the limits of float point arithmetic. Because the decimal coordinates of your line and point have no exact binary representation, they will never exactly intersect. Regard:

```python
>>> LineString([(0.0, 0.0), (2.1, 1.2)]).distance(Point(0.7, 0.4))
4.5902072731403177e-17
```

Shapely can't be used to determine if points are on lines for all possible coordinate values. It is reliable for determining overlap of 2-D regions that have a finite size, but might fail to detect that shapes touch at exactly one point for the same reason point and line intersection is unreliable.
