### ISSUE TITLE
LinearRing.touches returns False?

### ISSUE THREAD

**Issue by shongololo** [Toblerity/Shapely#427]
This surprised me:

```python
geometry.LinearRing([[0,0], [1,1], [1,0], [0,0]]).touches(geometry.LinearRing([[0,0], [-1,-1], [-1,0], [0,0]]))
# returns False
geometry.Polygon([[0,0], [1,1], [1,0], [0,0]]).touches(geometry.Polygon([[0,0], [-1,-1], [-1,0], [0,0]]))
# returns True
```

Is this the intended behaviour?

I also noticed that LinearRing.contains will also not return True in such cases as it encircles another LinearRing, but in that case it makes sense since a LinearRing is not 'filled'.

**Comment by sgillies** [comment]
Furthermore

```
>>> geometry.Polygon([[0,0], [1,1], [1,0], [0,0]]).touches(geometry.LinearRing([[0,0], [-1,-1], [-1,0], [0,0]]))
True
```

The exact semantics of "touches" have slipped my mind, but I'll go to the sources and report back.

**Comment by sgillies** [comment]
Here we go: http://postgis.net/docs/ST_Touches.html (Shapely uses the same geometry lib as PostGIS).

> ST_Touches — Returns TRUE if the geometries have at least one point in common, but their interiors do not intersect.

Understanding geometry boundaries and interiors and how different they are between lines (rings) and polygons is the key. For a polygon, the boundary is the set of points along the enclosing ring and the interior is the set of points within. For a ring, the interior is the set of points along the ring, and the boundary is the null set – it's a closed ring with no beginning or end. Since "touches" means boundary intersection *only* (no interior intersection), a ring cannot touch anything. A `LineString` with the same coords as the linear ring *does* have a non-null boundary and so

```
>>> geometry.Polygon([[0,0], [1,1], [1,0], [0,0]]).touches(geometry.LineString([[0,0], [-1,-1], [-1,0], [0,0]]))
True
```

Shapely is doing the right thing as defined by DE-9IM.

**Comment by shongololo** [comment]
Thanks, appreciate the explanation.

**Comment by sgillies** [comment]
My explanation was wrong, @shongololo. Sorry. Rings *can* touch other geometry types, but cannot touch other rings.

**Comment by shongololo** [comment]
Thank you, good to know this for future reference.
