### ISSUE TITLE
Community: Broken link

### ISSUE THREAD

**Issue by rjpereira** [Toblerity/Shapely#430]
Hi.
The main page of the project points to a support community at a web site which seems to have its domain expired and doesn't work anymore. Is there an alternative recommended way where I could reach the community of users of Shapely to ask a question ?

Thanks

**Comment by snorfalorpagus** [comment]
There is a fairly active community on GIS.SE: https://gis.stackexchange.com/questions/tagged/shapely

**Comment by sgillies** [comment]
I'll second this. If you tag your question with "shapely" on GIS-SE it will
be seen by a bunch of knowledgeable folks.

If you have questions or concerns about development of the software itself,
don't hesitate to open a new issue here.

On Nov 18, 2016 12:03 PM, "Joshua Arnott" <notifications@github.com> wrote:

There is a fairly active community on GIS.SE: https://gis.stackexchange.com/
questions/tagged/shapely

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Toblerity/Shapely/issues/430#issuecomment-261506095>,
or mute the thread
