### ISSUE TITLE
lib geos_c not found when using shapely on centos

### ISSUE THREAD

**Issue by geoHeil** [Toblerity/Shapely#466]
When installing shapely for a current centos 7.3 (minimal) for python 2.9 I get 
OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].
when trying to use geopandas.

When trying to install `sudo yum install libgeos-dev` yum tells me the package is not found. Is there a repository I am missing?

# edit
http://trac.osgeo.org/geos is pointing to https://yum.postgresql.org/repopackages.php#pg96 for the RPM but still after rpm -Uvh https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm the installation candidate is not found:
```

sudo yum install libgeos-dev
Geladene Plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.inode.at
 * epel: mirrors.nic.cz
 * extras: mirror.inode.at
 * updates: mirror.inode.at
Kein Paket libgeos-dev verfügbar.
```

**Comment by snorfalorpagus** [comment]
I'm closing this as it's not a Shapely issue.

According to the GEOS website several Linux distributions provide a package for libgeos, but CentOS is not listed.

GEOS isn't difficult to build from source, so that's another option for you. In fact the build instructions specifically mention CentOS: https://trac.osgeo.org/geos/wiki/BuildingOnUnixWithAutotools
