### ISSUE TITLE
SIGSEGV when using an invalid LineString with speedups enabled

### ISSUE THREAD

**Issue by clement-tourriere** [Toblerity/Shapely#486]
## Steps to reproduce the problem.

Without numpy installed : 

```
from shapely.geometry import LineString
ls = LineString([[-122.185933073564, 37.3629353839073]])
ls.geom_type
```

## Shapely version

Shapely==1.6b4

## Cause

It seems to come from geos_linestring_from_py method in _speedups.pyx. This method casts GEOSGeom_createLineString_r(handle, cs) into a uintptr_t. 
If the shape is null, it returns `0` instead of None in python.

## Resolution

Replace : `return <uintptr_t>GEOSGeom_createLineString_r(handle, cs), n` 
by : `return GEOSGeom_createLineString_r(handle, cs), n` 
in _speedups.pyx

OR 

Raise an exception if a LineString contains less than two coordinates tuples (in linestring.py and _speedups.pyx)

**Comment by snorfalorpagus** [comment]
Confirmed. The issue is also present with speedups disabled. If NumPy is available there is a specific check for the length of the coordinate sequence, but this isn't present in the non-numpy branch (in Python or Cython). It's easy to add the same check in, but I wonder if we should also check createLineString doesn't return a null pointer before returning the result.
