### ISSUE TITLE
`orient` function should work on arbitrary geometries

### ISSUE THREAD

**Issue by daniel-j-h** [Toblerity/Shapely#635]
Context: https://github.com/mapbox/robosat/pull/113

The `orient` function currently only works on polygons. If we want to orient multi-polygons correctly we need to manually iterate through a multi-polygon's geoms and orient all of them.

The `orient` function should ideally work on arbitrary geometries so that the user does not have to do manual type-checks.

A couple of questions:
- Do we really want `orient` for all geometries? Or only for polygons and multi-polygons?
- What's the best way to implement this, simply providing another `orient` function in the multipolygon file applying the polygon orient function to all its geoms?
- Tests - what else do we need?

cc @sgillies

**Comment by sgillies** [comment]
@daniel-j-h since the semantics of `orient` are to ensure that signed areas of a geometry are positive or negative, it only applies to 2-dimensional geometries: polygons, multipolygons, and objects of those kinds that make up a geometry collection.

@snorfalorpagus what would you think about adding a more general `orient` function to shapely.ops or another module?

**Comment by drnextgis** [comment]
Fixed via https://github.com/Toblerity/Shapely/commit/b2c562c6a78cf86fa284ca045946b389dfdf1fe8
