### ISSUE TITLE
`shapely.wkb.loads` crashes Python with segmentation fault

### ISSUE THREAD

**Issue by ldesousa** [Toblerity/Shapely#663]
## Expected behavior and actual behavior.

I would like to import a GeoJSON polygon to Shapely from a WKB. Instead Python crashes with a segmentation fault.

## Steps to reproduce the problem.

Download Goode's Homolosine counter-domain:
https://zenodo.org/record/1475153/files/CounterDomain.geojson?download=1

Execute the following code:

```
from osgeo import ogr
import shapely.wkb

driver = ogr.GetDriverByName("GeoJSON")
dataSource = driver.Open("CounterDomain.geojson", 0)
layer = dataSource.GetLayer()
counterDomain = shapely.wkb.loads(layer.GetFeature(0).GetGeometryRef().ExportToWkb(), hex=True)
```

## Operating system

Ubuntu 18.04

## Shapely version and provenance

Version 1.6.4, installed from the universe repository:

```
$ apt policy python3-shapely
python3-shapely:
  Installed: 1.6.4-1
  Candidate: 1.6.4-1
  Version table:
 *** 1.6.4-1 500
        500 http://ch.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by sgillies** [comment]
@ldesousa can you copy the wkb (hex encoded or straight bytes) here? I don't want to install the OGR Python bindings to test shapely.

**Comment by mwtoews** [comment]
I'd expect OGR to crash with `layer.GetFeature(0).GetGeometryRef().ExportToWkb()`

This is a known ["gotcha" described here](https://trac.osgeo.org/gdal/wiki/PythonGotchas#Pythoncrashesifyouuseanobjectafterdeletinganobjectithasarelationshipwith), and basically it should normally be split into a few lines with extra objects to avoid dereferencing, i.e.:
```python
feature = layer.GetFeature(0)
geomref = feature.GetGeometryRef()
```
However, there other bad news with this geometry:
```python
geomref.IsValid()
# False ; ERROR 1: IllegalArgumentException: Points of LinearRing do not form a closed linestring
geomrefhex = geomref.ExportToWkb().hex()
geom = shapely.wkb.loads(geomrefhex, hex=True)
# raises WKBReadingError: Could not create geometry because of errors while reading input.
# with logger output: IllegalArgumentException: Points of LinearRing do not form a closed linestring
```
This can be fixed by closing the linear ring, i.e. repeat the first and last coordinates. If you made the Json file, then you can fix the file yourself.

**Comment by mwtoews** [comment]
(Closing, as I'm 99% sure the crash was from OGR, and the invalid geometry cannot be read by GEOS)

**Comment by sgillies** [comment]
Thanks @mwtoews !
