### ISSUE TITLE
ops unions' docstrings are conflicting

### ISSUE THREAD

**Issue by kannes** [Toblerity/Shapely#667]
https://github.com/Toblerity/Shapely/blob/master/shapely/ops.py#L120 says for cascaded_union

> This is the most efficient method of dissolving many polygons.

and https://github.com/Toblerity/Shapely/blob/master/shapely/ops.py#L136 for unary_union

> This method replaces cascaded_union as the prefered method for dissolving many polygons.

Finally the docs include https://shapely.readthedocs.io/en/stable/manual.html#shapely.ops.cascaded_union

> In 1.2.16 shapely.ops.cascaded_union() is superceded by shapely.ops.unary_union() if GEOS 3.2+ is used.

Now cascaded_union might still be most efficient but to me it sounds like that docstring should be replaced with a suggestion to use unary_union instead nowadays?

(If someone touches either the docs or docstrings on this, also homogenise the functions' short summary lines please.)

**Comment by snorfalorpagus** [comment]
The documentation is actually incorrect. `unary_union` is used in place of `cascaded_union` in GEOS >= 3.3, not 3.2. I'm assuming this is just a mistake in the docs rather than an error and that unary_union isn't available in 3.2.

https://github.com/Toblerity/Shapely/blob/master/shapely/geos.py#L823

I don't think the explanation in the docs is very clear either:

> In 1.2.16 shapely.ops.cascaded_union() is superceded by shapely.ops.unary_union() if GEOS 3.2+ is used. The unary union function can operate on different geometry types, not only polygons as is the case for the older cascaded unions.

What does superseded mean in this context? Is the old function still available but you should use the new one? Was it replaced? Answer: it was replaced, and the old name is aliased.

Also the docs have an example for cascade_union but not unary_union.

https://shapely.readthedocs.io/en/stable/manual.html#shapely.ops.unary_union

**Comment by kannes** [comment]
I now looked at both JTS and GEOS docs and neither are clear about the benefits or drawback of the two approaches. Cascaded union is older, unary union is newer.

- https://geos.osgeo.org/doxygen/classgeos_1_1operation_1_1geounion_1_1CascadedUnion.html#details
- https://locationtech.github.io/jts/javadoc/org/locationtech/jts/operation/union/CascadedPolygonUnion.html

- https://geos.osgeo.org/doxygen/classgeos_1_1operation_1_1geounion_1_1UnaryUnionOp.html
- https://locationtech.github.io/jts/javadoc/org/locationtech/jts/operation/union/UnaryUnionOp.html

So neither JTS nor GEOS marked one of the approaches as deprecated or superseded. Bleargh, explicite documentation rules. :o)

I will prepare a nice PR with a switch of the doc's focus from cascaded_union to unary_union. And I will boldly mention that cascaded_union has not been used since 1.2.16. ;)

**Comment by kannes** [comment]
Oh come on, this was done in https://github.com/Toblerity/Shapely/commit/524f26fdc9934de99bc5279863df9b560c36a8e3 without any notice.

**Comment by kannes** [comment]
Fixed in https://github.com/Toblerity/Shapely/commit/db293a31ff98bef7a082e37740cdde72bc3dab0c
