### ISSUE TITLE
Document possibility of setting geometry attributes

### ISSUE THREAD

**Issue by torfsen** [Toblerity/Shapely#669]
The 1.6 docs don't mention that one can set arbitrary attributes on a geometry object, and the comments in (the rather old) issue #48 pretty much tell you not to do it.

However, in [a comment in #618](https://github.com/Toblerity/Shapely/issues/618#issuecomment-408891713), @sgillies mentions:

> You can add attributes to a geometry object after it has been created because these geometry objects store their attributes in a `__dict__` member (`geom.myattr` gets read as `geom.__dict__['myattr']`).

So it is indeed possible to safely add custom attributes to geometry objects -- a really nice feature to have! The docs should be updated to mention this.

**Comment by sgillies** [comment]
@torfsen since this feature is a built in feature of Python objects, I don't see that it needs to be especially highlighted. I'm temporarily out of time to work on Shapely issues that aren't highest priority, so I'd like to close this one up if you don't mind. But if you've got a PR to submit for the docs, I'll be glad to leave this open.

**Comment by torfsen** [comment]
@sgillies My bad, I misread your comment and thought that you had implemented a separate dict to store user-attributes in.
