### ISSUE TITLE
Unable to unpickle an object created from a class that inherits from shapely.geometry Polygon

### ISSUE THREAD

**Issue by matejt** [Toblerity/Shapely#702]
## Expected behavior and actual behavior.
Error on the line: p2 = pickle.loads(pickled):
    TypeError: __init__() missing 2 required positional arguments: 'my_attr' and 'bound_wkt'

## Steps to reproduce the problem.
import pickle
from shapely.geometry import Polygon
from shapely.wkt import loads as shapely_wkt_loads

class MyPoly(Polygon):
    def __init__(self, my_attr, bound_wkt):
        self.my_attr = my_attr
        super(MyPoly, self).__init__(shapely_wkt_loads(bound_wkt))

def main():
    bound_wkt = 'POLYGON  (( -79.240 39.277, -79.239 39.277, -79.239 39.278, -79.240 39.278, -79.240 39.277))'
    p = MyPoly('abc', bound_wkt)

    pickled = pickle.dumps(p)
    p2 = pickle.loads(pickled)
    print (p2)

if __name__ == '__main__':
    main()

## Operating system
Windows 7

## Shapely version and provenance
Shapely (1.6.4.post1) installed from whl file downloaded from (https://www.lfd.uci.edu/~gohlke/pythonlibs/)

**Comment by sgillies** [comment]
@matejt I'm sorry to say it, but shapely's pickling support doesn't support subclassing. See the implementation at https://github.com/Toblerity/Shapely/blob/master/shapely/geometry/base.py#L244.  I don't think we are going to change this soon.

If you can't alter your program to use shapely via composition instead of inheritance, you will need to override `__reduce__` and `__setstate__` in your class.
