### ISSUE TITLE
Why don't geometric objects have `__repr__`?

### ISSUE THREAD

**Issue by LostFan123** [Toblerity/Shapely#718]
According to Python docs on `__repr__` ([here](https://docs.python.org/reference/datamodel.html#object.__repr__) and [here](https://docs.python.org/library/functions.html#repr)), it is used for a string representation of an object, and "_should look like a valid Python expression that could be used to recreate an object with the same value_". Also: it "_is typically used for debugging, so it is important that the representation is information-rich and unambiguous._"  

But, as it's not implemented, what I get is something like this:
```python
>>> from shapely.geometry import Point
>>> [Point(1, 1), Point(2, 2)]
[<shapely.geometry.point.Point at 0x7fc638049cf8>,
 <shapely.geometry.point.Point at 0x7fc638049978>]
```
or another example:
```python
>>> from typing import NamedTuple
>>> class Site(NamedTuple):
...     point: Point
...     area_requirement: float    
>>> Site(point=Point(1, 1), area_requirement=0.25)
Site(point=<shapely.geometry.point.Point object at 0x7fc62fdb1be0>, area_requirement=0.25)
```
So, how about implementing it? So, the expected output would be:
```python
>>> [Point(1, 1), Point(2, 2)]
[Point(1, 1), Point(2, 2)]
```
and
```python 
>>> Site(point=Point(1, 1), area_requirement=0.25)
Site(point=Point(1, 1), area_requirement=0.25)
```
---
Shapely version: 1.6.4.post1, installed from conda.

**Comment by snorfalorpagus** [comment]
I have a feeling this has been discussed before but I can't find the issue.

This makes sense for simple geometries like `Point` but how should a `LineString` with 50,000 coordinates be handled?

**Comment by LostFan123** [comment]
@snorfalorpagus I'm sorry but I'm not exactly sure what your point is. Why should it be handled in a different way? If it's about a number of objects or the length of the output then, for example, nothing prevents me from doing something like this:
```python
>>> from pathlib import Path
>>> from itertools import repeat
>>> paths = list(repeat(Path(), 1_000_000))
>>> repr(paths)
# this will give a veeery long repr
```

**Comment by sgillies** [comment]
@snorfalorpagus I don't think that length of the representation is a disqualifier, we don't truncate `str(geom)` in any case, or guard users against long WKT strings. 

@LostFan123 I think that `"Point(1, 1)"` is in one way *more* ambiguous than `"<shapely.geometry.point.Point at 0x7fc638049cf8>"`: it doesn't tell you which namespace Point comes from, and there are many Point classes out there. `"shapely.geometry.point.Point(1, 1)"` is unambiguous, but doesn't automatically round-trip through eval because there's no guarantee that shapely.geometry.point.Point is a valid name in your program. The repr-eval use case only holds for builtin types.

Changing __repr__ for geometries isn't high priority for me, but I would review a PR.

**Comment by dashesy** [comment]
It is very common to have a simple line like

```python
___repr__ == ___str___
```

for each class that has `str` but not `repr`. But it is more common to just provide `___repr__` because then by default it will be also used for `__str__`
