### ISSUE TITLE
Made a `shapely-helper` package

### ISSUE THREAD

**Issue by SimonBiggs** [Toblerity/Shapely#815]
Hi,

I wanted to give you a heads up, I have created a `shapely-helper` package on pypi so that my library [`pymedphys`](https://docs.pymedphys.com/) can depend on `shapely` while still have my package be pip installable on Windows.

The source code for the `shapely-helper` package can be found at:
https://github.com/pymedphys/pymedphys/tree/a10f1eb/misc/shapely-helper

The pypi record is at:
https://pypi.org/project/shapely-helper/

If you would prefer I name it differently, let me know.

Cheers,
Simon

**Comment by sgillies** [comment]
@SimonBiggs perhaps "pymedphys-helper" or "pymedphys-deps" would be a more accurate name since the package doesn't help or extend shapely?

I'm sorry that this project hasn't been able to provide windows platform wheels containing compiled modules. It's mostly due to lack of time and windows experience among the principal contributors. We've been relying on Conda and Conda-Forge to pick up the slack. The current issues are being tracked at https://github.com/Toblerity/Shapely/issues/367. 

Have you considered bundling shapely with releases of pymedphys instead of packaging it separately? That approach would have its own issues, of course, but might be less complicated for users.

**Comment by SimonBiggs** [comment]
> I'm sorry that this project hasn't been able to provide windows platform wheels containing compiled modules. It's mostly due to lack of time and windows experience among the principal contributors. We've been relying on Conda and Conda-Forge to pick up the slack. The current issues are being tracked at #367.

No need to be sorry, thank you for the wonderful tool you've built. I do imagine that GitHub Actions could go a long way to make wheels. Do you know what scripts are used to build the following wheels?

https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely

Potentially one of those could run in GitHub Actions triggered by a release, and upload the wheels to PyPI. I could help with the GitHub actions side of things if there is a clearly defined Windows build script.

**Comment by sgillies** [comment]
Let's continue the Windows wheel discussion in #367. We've got an AppVeyor config committed to the Shapely repo, but haven't set it up yet. Linux and OS X wheels are being built by https://github.com/sgillies/shapely-wheels, which runs on Travis CI.

I'm going to close this issue up. Would you consider renaming your PyPI project or at least adding a description so that users don't confuse it with a package that extends Shapely?

**Comment by SimonBiggs** [comment]
> I'm going to close this issue up. Would you consider renaming your PyPI project or at least adding a description so that users don't confuse it with a package that extends Shapely?

Will do, I've already released a version that depends on it, so I would need to go through a deprecation process. In the interim a description would be helpful I imagine.

**Comment by sgillies** [comment]
@SimonBiggs I just remembered to follow up here: we have some wheels for Windows on PyPI starting with 1.7.0 https://pypi.org/project/Shapely/1.7.0/#files.

**Comment by SimonBiggs** [comment]
> @SimonBiggs I just remembered to follow up here: we have some wheels for Windows on PyPI starting with 1.7.0 https://pypi.org/project/Shapely/1.7.0/#files.

Oh that completely makes my day! :) Thank you!
