### ISSUE TITLE
equals is True but almost_equals is False

### ISSUE THREAD

**Issue by dashesy** [Toblerity/Shapely#889]
## Expected behavior and actual behavior.

`almost_equals` should return True, if `equals` is True.

## Steps to reproduce the problem.

```python
import numpy as np
from shapely.geometry import Polygon, box

coords = np.array(
       [[ 577., 1250.],
       [ 593., 1325.],
       [2447., 1002.],
       [2447.,  945.]], dtype=np.float32
)

p = Polygon(coords)
rect = Polygon.from_bounds(*p.bounds)
rect2 = box(*p.bounds)

print(rect.equals(rect2))
print(rect.almost_equals(rect2))
```

## Operating system

Ubuntu Linux 16

## Shapely version and provenance

1.7.0

**Comment by jorisvandenbossche** [comment]
@dashesy this is the expected behaviour, although certainly a "gotcha" when using `almost_equals`.

If you look at the two rectangles:

```
In [12]: print(rect) 
POLYGON ((577 945, 577 1325, 2447 1325, 2447 945, 577 945))

In [13]: print(rect2) 
POLYGON ((2447 945, 2447 1325, 577 1325, 577 945, 2447 945))
```

you can see they are not "exactly" equal (the order of the coordinate pairs differ). The `equals` method check topological / spatial equality, and thus returns True as both polygons describe the same rectangle area. 
But the `almost_equals` method, on the other hand, checks if two objects are structurally equal. This method uses exact coordinate equality, which requires coordinates to be equal (within specified tolerance) and and in the same order for all components of a geometry.

There is actually a similar method `equals_exact` (which IMO better reflects this constraint in its name as `almost_equals`). 

This is mentioned in the docstring:

https://github.com/Toblerity/Shapely/blob/8d5a7e2a89ff142669161fd8a5662d60fe3de09d/shapely/geometry/base.py#L783-L790

But it seems that a similar note would be welcome in the `almost_equals` entry in the manual, as there this constraint is not very explicitly mentioned: https://shapely.readthedocs.io/en/latest/manual.html#object.almost_equals

**Comment by sgillies** [comment]
@dashesy we could deprecate almost_equals (confusing name, I agree) and move its tolerance argument to equals_exact (default tolerance of 0). Would that improve the situation from your perspective?

**Comment by dashesy** [comment]
@sgillies yes I think that makes everything simpler and clearer.

**Comment by jorisvandenbossche** [comment]
I would be +1 on deprecating `almost_equals`. 
(note that it's `equals_exact` that has a tolerance argument, `almost_equals` has a "decimals" argument which gets translated to a tolerance)

I was looking at JTS some time ago (https://docs.geotools.org/latest/userguide/library/jts/equals.html) for possible inspiration, and they have a "equalsTopo" (for a more explicit name for "equals"), and a "equalsNorm" (which does an exact equals but automatically normalizes the geometries first)

I think certainly the normalization (either as separate function as JTS, or as option in `equals_exact`) would be useful (I think it will be more accessible than a separate normalization function).

**Comment by tomplex** [comment]
Would it be better to add a `normalize` kwarg to `equals_exact` or to expose a separate `equals_normalized` method?

**Comment by heidimhurst** [comment]
Old issue, but would like to bump that this is still a real pain point!

**Comment by snowman2** [comment]
Moved almost equals to discussion to #1555
