### ISSUE TITLE
unexpected Linestring when using LinearRing.intersection(MultiLineString)

### ISSUE THREAD

**Issue by vivekbharadhwajsa** [Toblerity/Shapely#918]
Hello, 
When i convert a polygon into a LinerRing and then check the intersection of LinearRing with the MultiLineString, I get a list of the intersection points with one LineString and all the Point and LineString are put together in a GeometrySequence object. I don't understand why a LineString has to appear when LinearRing.intersection(MultiLineString) is used. 
![err](https://user-images.githubusercontent.com/51442925/82800408-f104a180-9e7b-11ea-837e-429ab8ea1752.png)
if you look at the last in the image, there is an unexpected LineString object after the intersection is done. 
Can you let me know what is the issue or how do i make sure that i get only Point objects when is use LinearRing.intersection(MultiLineString) ?

**Comment by tomplex** [comment]
It depends on your input data. If your MultiLineString shares a segment of your LinearRing, then when you intersect them, you will get back a LineString for that segment because the intersection between the two geometries *isn't* a point, it's a LineString. That follows directly to your next question: you get back a GeometryCollection because your intersection returned multiple types of geometries, and a GeometryCollection is the only type which can hold multiple distinct types of geometries.

Consider this example:

<img width="445" alt="Screenshot 2020-05-25 16 24 06" src="https://user-images.githubusercontent.com/8109856/82841460-2b823480-9ea4-11ea-8c2f-4d39a8dc463a.png">

Here we have a Polygon & and a MultiLineString. One Linestring in the MultiLineString runs across the polygon, and another shares the right hand side border of the polygon. They are represented in WKT like so:

```
POLYGON ((0 0, 0.5 0, 1 0, 1 0.5, 1 1, 0.5 1, 0 1, 0 0.5, 0 0))
MULTILINESTRING ((-0.2 0, 0.2 0.6, 0.5 1.1), (0.9 -0.1, 1 0, 1 0.5, 1 1, 0.7 1.1))
```

Taking the intersection of the *exterior* of the polygon (which is a LinearRing) and the MultiLineString gives us back a GeometryCollection, because the intersection between the two is defined both by Points and LineStrings:

<img width="482" alt="Screenshot 2020-05-25 16 30 53" src="https://user-images.githubusercontent.com/8109856/82841725-1d80e380-9ea5-11ea-9cc5-8b50e726fd9d.png">

If you only want to get back points, then you will need to iterate through the GeometryCollection and return the constituent points of each geometry within.

**Comment by sgillies** [comment]
Thanks @tomplex !
