### ISSUE TITLE
nearest_points on a LineString not returning a Point on the LineString

### ISSUE THREAD

**Issue by DrSchottky** [Toblerity/Shapely#934]
Hi, I'm using Shapely (1.7, Python 3.8.2, amd64) to split a LineString at Points.
I know that to use split() points have to be exactly on the line (distance 0) and since it's not my case I'm using nearest_points() to find the closest points on the line. 
It worked most of the time, but I have a LineString/Point that's not working the expected way: in that case the tuple returned by nearest_points() contains two identical Point, also identical to the Point supplied as argument.
`p == nearest_points(ls, p)[0] == nearest_points(ls, p)[1]`
and of course the resulting point is not exactly on the line and can't be used with split()

[Here's](https://github.com/Toblerity/Shapely/files/4808073/script.txt) a script showing the issue
Is it an expected behavior? How can I split that LineString?

Thank you

**Comment by sgillies** [comment]
It's inherently hard to split a line using a point unless the line is snapped to the point in advance. See http://postgis.net/docs/ST_Split.html for a discussion of the problem. Can you try https://shapely.readthedocs.io/en/latest/manual.html#snapping and see of that helps? I'm going to close this ticket because snapping is our only solution.
