### ISSUE TITLE
accessing only the corners of a polygon 

### ISSUE THREAD

**Issue by vivekbharadhwajsa** [Toblerity/Shapely#939]
Hello, 
I want to know if there is a way to access only the corners in a polygon (not the points on the exterior which is through polygon.exterior.coords), I want only the sharp corners of a polygon. Or any other links or methods to get the corners are appreciated. 
Thanks

**Comment by mwtoews** [comment]
I'm assuming you mean convex vertices, based on identifying coordinates with interior facing angles of <180°? No, there isn't this type of functionality in Shapely (or parent libraries GEOS/JTS), but it can be derived from the `polygon.exterior.coordinates` property along with some trigonometry.

The best forum to ask this question is on [GIS.StackExchange](https://gis.stackexchange.com) as I'm certain you'll get some some interesting ideas.

**Comment by sgillies** [comment]
I'm closing this one because the issue tracker isn't for usage questions. @mwtoews thanks for the support. @vivekbharadhwajsa you may have some success with simplifying your geometries using `simplify()`: in theory it might simplify a densely noded rectangle into a rectangle with only four vertices.
